server:
  port: 9103

spring:
  application:
    name: gateway-server
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: FNTEC
          uri: lb://FNTEC
          predicates:
            - Path=/FNTEC/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/


