server:
  port: 9103

spring:
  application:
    name: gateway-server
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter
        - id: FNTEC
          uri: lb://FNTEC
          predicates:
            - Path=/FNTEC/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970